### ISSUE TITLE
detection of lexer fails if gawk isn't installed

### ISSUE THREAD

**Issue by kl-git** [CoeJoder/lessfilter-pygmentize#2]
Hi @CoeJoder 

I am enjoying your script very much. Very helpful, thanks so much.

While using it on several machines with different setups, I discovered, that the awk script to decode the shebang uses gawk syntax. The script failed since gawk wasn't installed and awk was used.

Rewriting like this should do the trick with awk:
```
lexer=$(head -n 1 "$path" | grep '^#\!' | awk -F" " '{ if (/env/) { print $2 } else { sub( /.*\//, ""); print $1;} }')
```

All the best for a prosperous year 2023,

Klaus

**Comment by CoeJoder** [comment]
Thanks for this improvement!  Happy New Year
